################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "D:/SSD Dados/Documents/Vivado/trabalho_afinador/trabalho_afinador_vivado/trabalho_afinador_vivado.xpr"
set rc [catch {
  source -notrace "D:/SSD Dados/Documents/Vivado/serial_file_echo/-L xpm"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"D:/SSD Dados/Documents/Vivado/serial_file_echo/-L xpm\""
}
close_project
